// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outside voice on a jar's identity, for artifacts Modrinth does not
 * carry. Keyed by content, so a rewritten version string inside the jar does
 * not move it.
 */
export type CurseForgeIdentity = { fingerprint: number, 
/**
 * Absent when the fingerprint matched nothing, which is the answer worth
 * having: this file is published neither here nor on Modrinth.
 */
project_id: number | null, file_id: number | null, 
/**
 * The name the publisher gave the file, to be believed over the version
 * string inside the jar.
 */
display_name: string | null, file_name: string | null, 
/**
 * False when the project's author has turned off third-party
 * distribution. The file can still be named, but the mirror must not
 * serve it on CurseForge's behalf.
 */
distributable: boolean, };
