// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mod a pack pinned twice through two different sources.
 */
export type DuplicateMod = { 
/**
 * The mod as the registry names it.
 */
name: string, 
/**
 * Every row that pinned it, in declaration order.
 */
filenames: Array<string>, };
