// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side of [`ModEnv`]: `required` when the pack locks the mod, `optional`
 * when it can be switched off, `unsupported` when that side has no use for it.
 */
export type EnvSupport = "required" | "optional" | "unsupported";
