// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionRow } from "./VersionRow";

/**
 * One artifact resolved by hash -- the Modrinth `version_file/{hash}` analog:
 * the file row, the release it belongs to, and the owning mod's identity.
 * Backs the public `GET /v1/files/{sha1}`.
 */
export type FileDetail = { mod_id: number, 
/**
 * canonical_name -> slug -> modid -> `#<id>`, resolved server-side.
 */
name: string, slug: string | null, version_number: string, channel: string, 
/**
 * Carries the CurseForge identity itself, so this view has one home for it
 * rather than a copy beside the file it describes.
 */
file: VersionRow, };
