// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurseForgeIdentity } from "./CurseForgeIdentity";
import type { VersionRow } from "./VersionRow";

/**
 * One artifact resolved by hash -- the Modrinth `version_file/{hash}` analog:
 * the file row, the release it belongs to, and the owning mod's identity.
 * Backs the public `GET /v1/files/{sha1}`.
 */
export type FileDetail = { mod_id: number, 
/**
 * canonical_name -> slug -> modid -> `#<id>`, resolved server-side.
 */
name: string, slug: string | null, version_number: string, channel: string, file: VersionRow, 
/**
 * What CurseForge says this artifact is, once it has been asked. `None`
 * means the question has not been put yet, which is not the same as
 * CurseForge not knowing it: that answers with a present value whose
 * `project_id` is absent.
 */
curseforge: CurseForgeIdentity | null, };
