// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvSupport } from "./EnvSupport";

/**
 * Whether a mod belongs in a client install and in a dedicated server
 * install. A singleplayer install is both at once and takes everything.
 */
export type ModEnv = { client: EnvSupport, server: EnvSupport, };
