// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { ModEnv } from "./ModEnv";
import type { Source } from "./Source";

export type ModEntry = { filename: string, sha1: string, size_bytes: number, required: boolean, 
/**
 * Install-time default for an optional entry (`required = false`): on unless
 * a curator opts it out. Omitted from the wire when true (the launcher's
 * SmrtModEntry defaults it to true), so only an opted-out mod carries it.
 */
default_enabled?: boolean, source: Source, display?: Display, 
/**
 * Curator-assigned stable identity, independent of the versioned filename. The
 * launcher keys an optional mod's on/off state by it so the choice survives a
 * version bump (ADR 0002); a Modrinth mod already has its project id, so this
 * carries the stable key for a self-hosted (smrt_cache) mod. Absent when unset.
 */
slug?: string, 
/**
 * Which installs the mod belongs in, in the vocabulary a Modrinth pack
 * file uses. Absent when the mirror could not classify the mod, which a
 * consumer reads as "belongs everywhere". A slice of the manifest
 * (`?side=`) drops what is `unsupported` on that side, except what a mod
 * it keeps hard-requires.
 */
env?: ModEnv, };
