// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackTier } from "./PackTier";
import type { VersionChannel } from "./VersionChannel";
import type { Visibility } from "./Visibility";

export type PackSummary = { pack_id: string, display_name: string, tagline: string, minecraft_version: string, latest_pack_version: string, tags: Array<string>, featured: boolean, 
/**
 * Square pack icon. Renders in BrowsePackCard avatar slot +
 * BrowsePackDetail hero on the launcher.
 */
icon_url?: string, 
/**
 * Wide hero image. Renders behind BrowsePackDetail hero text;
 * falls back to the launcher's mirror gradient when absent.
 */
banner_url?: string, 
/**
 * Optional marketing screenshots. Rendered in a horizontal
 * scroller on BrowsePackDetail when non-empty.
 */
gallery_urls: Array<string>, 
/**
 * Long-form CommonMark description for the BrowsePackDetail
 * About section. HTML is not parsed by the launcher.
 */
description_md?: string, 
/**
 * The same tagline keyed by language tag (`{"en": "...", "ru": "..."}`),
 * for a reader who does not read the language the untagged one is written
 * in. Same rule as `PackManifest::changelog_i18n`: prefer the user's
 * language, fall back to the untagged field, and read a missing key as
 * "not written" rather than "written as nothing".
 */
tagline_i18n?: { [key in string]: string }, 
/**
 * The same description per language tag; see `tagline_i18n`.
 */
description_md_i18n?: { [key in string]: string }, 
/**
 * GitHub uid of the pack owner. Official packs are owned by the operator;
 * community packs by their member. Server-controlled -- set at authoring.
 */
owner: number, tier: PackTier, visibility: Visibility, 
/**
 * Source pack id when this pack is a fork; absent otherwise.
 */
fork_of?: string, 
/**
 * When the latest build was produced (the latest manifest's
 * `generated_at`, RFC 3339). Derived at read time from the manifest --
 * never persisted in `summary.json`; absent when the pack has no build.
 */
latest_built_at?: string, 
/**
 * Channel of `latest_pack_version`; same derivation and absence rules
 * as `latest_built_at`.
 */
latest_channel?: VersionChannel, };
