// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The launcher-facing presence class of one mod in one pack -- the computed
 * output of the two axes plus the dependency graph. `Required` means the
 * graph locked the mod, and never names a client-side one (the client-mod
 * invariant); a server-side mod reads required when an enabled mod cannot
 * start without it. The optional classes carry the side so a launcher can
 * badge the toggle;
 * `Coremod` marks a jar that is not a mod at all (a bare ASM/loader plugin),
 * which is always toggleable.
 */
export type PresenceClass = "required" | "optional_client" | "optional_server" | "optional_both" | "coremod";
