// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveConflict } from "./ActiveConflict";
import type { CapabilityOverlap } from "./CapabilityOverlap";
import type { DuplicateMod } from "./DuplicateMod";
import type { ForcedClientEdge } from "./ForcedClientEdge";
import type { LoaderMismatch } from "./LoaderMismatch";
import type { LoaderVersionIssue } from "./LoaderVersionIssue";
import type { MissingDep } from "./MissingDep";
import type { MixinGap } from "./MixinGap";
import type { SideDisagreement } from "./SideDisagreement";
import type { VersionIssue } from "./VersionIssue";

/**
 * The outcome of resolving a pack against the registry graph. Arrays are empty
 * when clean; `missing` and `conflicts` are the blocking problems, the rest are
 * advisory. All lists are sorted for a stable render.
 */
export type ResolveReport = { declared_mods: number, 
/**
 * How many declared jar mods are identified: a registry identity, or a valid
 * Modrinth pin the mirror has not harvested yet (present at build). The rest
 * are in `unresolved`.
 */
resolved_mods: number, 
/**
 * A hard dependency no present mod satisfies -- the pack would crash.
 */
missing: Array<MissingDep>, 
/**
 * One mod pinned twice, through two sources that look unrelated in the
 * config. Two builds of a mod in one instance is a crash, and the config's
 * own uniqueness check cannot see this one: it compares sources, and a
 * Modrinth project, a CurseForge project and a cached hash are three
 * different strings for the same mod. Only the registry knows they are.
 */
duplicate_mods: Array<DuplicateMod>, 
/**
 * Two present mods the graph says cannot run together, both in the default
 * install -- a live conflict the pack ships with.
 */
conflicts: Array<ActiveConflict>, 
/**
 * The same incompatibility, but with at least one side an opted-out optional
 * -- it only bites if the user turns that mod on, so it is advisory, not a
 * blocking problem (#9).
 */
optional_conflicts: Array<ActiveConflict>, 
/**
 * A capability more than one present mod provides -- usually redundant, and
 * the two may fight over the same hook.
 */
overlaps: Array<CapabilityOverlap>, 
/**
 * A present dependency whose shipped version sits outside a requirer's
 * declared window.
 */
version_issues: Array<VersionIssue>, 
/**
 * The same finding against the loader itself: a jar declaring a build of
 * the pack's own loader that the pinned one does not satisfy (#164).
 *
 * Filled by [`super::loaderreq::loader_windows`], not by [`resolve_pack`]:
 * the window is inside the jar, and a Modrinth pin's jar is not on this
 * disk, so answering needs I/O this pure pass has not got. A caller that
 * does not run that pass leaves it empty, which reads as "not checked" --
 * the same as every other fact the mirror has not looked up.
 */
loader_version_issues: Array<LoaderVersionIssue>, 
/**
 * Declared artifacts this pack's loader cannot run, with nothing present to
 * bridge them -- they will not load at all (#50).
 */
loader_mismatch: Array<LoaderMismatch>, 
/**
 * A required mixin whose target the pack's copy of the host no longer
 * carries (#145). The pack starts loading and dies during init.
 */
mixin_gaps: Array<MixinGap>, 
/**
 * Foreign-loader artifacts a present connector carries. Not a problem: they
 * load. Listed because it is worth knowing which mods in a forge pack are
 * actually fabric mods riding the bridge -- pull the connector and they all
 * go at once.
 */
loader_bridged: Array<LoaderMismatch>, 
/**
 * Declared jar mods with no identity and no valid pin: an un-harvested
 * `smrt_cache` upload the mirror has not read. Left unjudged, listed so the
 * operator knows coverage was partial. A Modrinth pin is not here -- it is a
 * valid declaration, counted in `resolved_mods`.
 */
unresolved: Array<string>, 
/**
 * How many version windows could not be checked because a version string was
 * not plainly comparable (a classifier suffix, an embedded MC prefix).
 */
version_windows_unchecked: number, 
/**
 * Declared jars that are not mods at all (bare coremods / ASM libraries):
 * always toggleable, never lockable -- listed so the curator knows why.
 */
coremods: Array<string>, 
/**
 * Mods the classifier could not decide a match policy for: shipped
 * toggleable rather than guessed. Curator material, not an error.
 */
unclassified: Array<string>, 
/**
 * Modrinth environment flags and the bytecode derivation disagree on the
 * side. The flags win by priority, but they are authored upstream and
 * sometimes wrong -- the curator should see the conflict.
 */
side_disagreements: Array<SideDisagreement>, 
/**
 * A declared (non-inferred) hard dependency targets a client-side mod --
 * a data error the build will refuse: a client mod is never
 * force-installed. Inferred edges never get here (the guard downgrades
 * them to soft before they can lock anything).
 */
forced_client_attempts: Array<ForcedClientEdge>, 
/**
 * Server-side mods in the pack: legitimate, but the client manifest ships
 * them opted out (never required, default-disabled).
 */
server_side: Array<string>, 
/**
 * `Recommends` targets absent from the pack -- curator suggestions with a
 * manual add action, never auto-added.
 */
suggestions: Array<string>, };
