// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceDecl = { "type": "modrinth", project_id: string, version_id: string, } | { "type": "curseforge", project_id: number, file_id: number, } | { "type": "github", 
/**
 * `owner/name`.
 */
repo: string, tag: string, asset: string, } | { "type": "smrt_cache", sha1: string, } | { "type": "smrt_static", rel_path: string, };
