// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Source = { "type": "modrinth", project_id: string, version_id: string, } | { "type": "curseforge", project_id: number, file_id: number, url: string | null, } | { "type": "smrt_cache", url: string, } | { "type": "smrt_static", url: string, };
