// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurseForgeIdentity } from "./CurseForgeIdentity";

/**
 * Q3: one version of a mod, with every loader it targets (`any` for a
 * loader-agnostic jar) and the Minecraft versions it was published for.
 */
export type VersionRow = { version: string, targets: Array<string>, mc_versions: Array<string>, sha1: string, size_bytes: number, filename: string | null, source: string, 
/**
 * True when the artifact's bytes are in the mirror's local cache, so it can
 * be re-added as a self-hosted `smrt_cache` source. Set by the handler
 * against the live cache inventory (not stored in the registry).
 */
cached: boolean, 
/**
 * Modrinth identity, when the artifact is one. Lets the panel re-add a
 * not-locally-cached Modrinth mod as a real Modrinth source.
 */
modrinth_project_id: string | null, modrinth_version_id: string | null, 
/**
 * What CurseForge says this artifact is, once it has been asked. `None`
 * means the question has not been put yet, which is not the same as
 * CurseForge not knowing it: that answers with a present value whose
 * `project_id` is absent.
 *
 * It rides on the file rather than beside it because a listing needs it as
 * much as a single lookup does. Without it every artifact Modrinth does not
 * carry reads as self-hosted, which is the `else` of a two-way question and
 * says nothing about whether anyone publishes the bytes.
 */
curseforge?: CurseForgeIdentity, };
